#cloud-config
package_upgrade: true
packages:
  - apt-transport-https

runcmd:
- echo 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list
- wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg
- apt update && apt install --yes openjdk-8-jre-headless unifi
- systemctl status --no-pager --full mongodb.service unifi.service